export type DiaPlano = {
  dia: number
  livro: string
  capitulos: string
  ref: string
  testamento: 'AT' | 'NT'
}

export const PLANO_LEITURA: DiaPlano[] = [
  // GÊNESIS (dias 1-17)
  { dia: 1,  livro: 'Gênesis',      capitulos: '1-3',   ref: 'Gn 1-3',    testamento: 'AT' },
  { dia: 2,  livro: 'Gênesis',      capitulos: '4-6',   ref: 'Gn 4-6',    testamento: 'AT' },
  { dia: 3,  livro: 'Gênesis',      capitulos: '7-9',   ref: 'Gn 7-9',    testamento: 'AT' },
  { dia: 4,  livro: 'Gênesis',      capitulos: '10-12', ref: 'Gn 10-12',  testamento: 'AT' },
  { dia: 5,  livro: 'Gênesis',      capitulos: '13-15', ref: 'Gn 13-15',  testamento: 'AT' },
  { dia: 6,  livro: 'Gênesis',      capitulos: '16-18', ref: 'Gn 16-18',  testamento: 'AT' },
  { dia: 7,  livro: 'Gênesis',      capitulos: '19-20', ref: 'Gn 19-20',  testamento: 'AT' },
  { dia: 8,  livro: 'Gênesis',      capitulos: '21-23', ref: 'Gn 21-23',  testamento: 'AT' },
  { dia: 9,  livro: 'Gênesis',      capitulos: '24-26', ref: 'Gn 24-26',  testamento: 'AT' },
  { dia: 10, livro: 'Gênesis',      capitulos: '27-29', ref: 'Gn 27-29',  testamento: 'AT' },
  { dia: 11, livro: 'Gênesis',      capitulos: '30-32', ref: 'Gn 30-32',  testamento: 'AT' },
  { dia: 12, livro: 'Gênesis',      capitulos: '33-35', ref: 'Gn 33-35',  testamento: 'AT' },
  { dia: 13, livro: 'Gênesis',      capitulos: '36-39', ref: 'Gn 36-39',  testamento: 'AT' },
  { dia: 14, livro: 'Gênesis',      capitulos: '40-42', ref: 'Gn 40-42',  testamento: 'AT' },
  { dia: 15, livro: 'Gênesis',      capitulos: '43-45', ref: 'Gn 43-45',  testamento: 'AT' },
  { dia: 16, livro: 'Gênesis',      capitulos: '46-48', ref: 'Gn 46-48',  testamento: 'AT' },
  { dia: 17, livro: 'Gênesis',      capitulos: '49-50', ref: 'Gn 49-50',  testamento: 'AT' },
  // JÓ (dias 18-31)
  { dia: 18, livro: 'Jó',           capitulos: '1-3',   ref: 'Jó 1-3',    testamento: 'AT' },
  { dia: 19, livro: 'Jó',           capitulos: '4-6',   ref: 'Jó 4-6',    testamento: 'AT' },
  { dia: 20, livro: 'Jó',           capitulos: '7-9',   ref: 'Jó 7-9',    testamento: 'AT' },
  { dia: 21, livro: 'Jó',           capitulos: '10-12', ref: 'Jó 10-12',  testamento: 'AT' },
  { dia: 22, livro: 'Jó',           capitulos: '13-15', ref: 'Jó 13-15',  testamento: 'AT' },
  { dia: 23, livro: 'Jó',           capitulos: '16-18', ref: 'Jó 16-18',  testamento: 'AT' },
  { dia: 24, livro: 'Jó',           capitulos: '19-21', ref: 'Jó 19-21',  testamento: 'AT' },
  { dia: 25, livro: 'Jó',           capitulos: '22-24', ref: 'Jó 22-24',  testamento: 'AT' },
  { dia: 26, livro: 'Jó',           capitulos: '25-27', ref: 'Jó 25-27',  testamento: 'AT' },
  { dia: 27, livro: 'Jó',           capitulos: '28-30', ref: 'Jó 28-30',  testamento: 'AT' },
  { dia: 28, livro: 'Jó',           capitulos: '31-33', ref: 'Jó 31-33',  testamento: 'AT' },
  { dia: 29, livro: 'Jó',           capitulos: '34-36', ref: 'Jó 34-36',  testamento: 'AT' },
  { dia: 30, livro: 'Jó',           capitulos: '37-39', ref: 'Jó 37-39',  testamento: 'AT' },
  { dia: 31, livro: 'Jó',           capitulos: '40-42', ref: 'Jó 40-42',  testamento: 'AT' },
  // ÊXODO (dias 32-44)
  { dia: 32, livro: 'Êxodo',        capitulos: '1-4',   ref: 'Êx 1-4',    testamento: 'AT' },
  { dia: 33, livro: 'Êxodo',        capitulos: '5-7',   ref: 'Êx 5-7',    testamento: 'AT' },
  { dia: 34, livro: 'Êxodo',        capitulos: '8-10',  ref: 'Êx 8-10',   testamento: 'AT' },
  { dia: 35, livro: 'Êxodo',        capitulos: '11-13', ref: 'Êx 11-13',  testamento: 'AT' },
  { dia: 36, livro: 'Êxodo',        capitulos: '14-16', ref: 'Êx 14-16',  testamento: 'AT' },
  { dia: 37, livro: 'Êxodo',        capitulos: '17-19', ref: 'Êx 17-19',  testamento: 'AT' },
  { dia: 38, livro: 'Êxodo',        capitulos: '20-22', ref: 'Êx 20-22',  testamento: 'AT' },
  { dia: 39, livro: 'Êxodo',        capitulos: '23-25', ref: 'Êx 23-25',  testamento: 'AT' },
  { dia: 40, livro: 'Êxodo',        capitulos: '26-28', ref: 'Êx 26-28',  testamento: 'AT' },
  { dia: 41, livro: 'Êxodo',        capitulos: '29-31', ref: 'Êx 29-31',  testamento: 'AT' },
  { dia: 42, livro: 'Êxodo',        capitulos: '32-34', ref: 'Êx 32-34',  testamento: 'AT' },
  { dia: 43, livro: 'Êxodo',        capitulos: '35-37', ref: 'Êx 35-37',  testamento: 'AT' },
  { dia: 44, livro: 'Êxodo',        capitulos: '38-40', ref: 'Êx 38-40',  testamento: 'AT' },
  // LEVÍTICO (dias 45-53)
  { dia: 45, livro: 'Levítico',     capitulos: '1-3',   ref: 'Lv 1-3',    testamento: 'AT' },
  { dia: 46, livro: 'Levítico',     capitulos: '4-6',   ref: 'Lv 4-6',    testamento: 'AT' },
  { dia: 47, livro: 'Levítico',     capitulos: '7-9',   ref: 'Lv 7-9',    testamento: 'AT' },
  { dia: 48, livro: 'Levítico',     capitulos: '10-12', ref: 'Lv 10-12',  testamento: 'AT' },
  { dia: 49, livro: 'Levítico',     capitulos: '13-16', ref: 'Lv 13-16',  testamento: 'AT' },
  { dia: 50, livro: 'Levítico',     capitulos: '17-19', ref: 'Lv 17-19',  testamento: 'AT' },
  { dia: 51, livro: 'Levítico',     capitulos: '20-22', ref: 'Lv 20-22',  testamento: 'AT' },
  { dia: 52, livro: 'Levítico',     capitulos: '23-25', ref: 'Lv 23-25',  testamento: 'AT' },
  { dia: 53, livro: 'Levítico',     capitulos: '26-27', ref: 'Lv 26-27',  testamento: 'AT' },
  // NÚMEROS (dias 54-65)
  { dia: 54, livro: 'Números',      capitulos: '1-3',   ref: 'Nm 1-3',    testamento: 'AT' },
  { dia: 55, livro: 'Números',      capitulos: '4-6',   ref: 'Nm 4-6',    testamento: 'AT' },
  { dia: 56, livro: 'Números',      capitulos: '7-9',   ref: 'Nm 7-9',    testamento: 'AT' },
  { dia: 57, livro: 'Números',      capitulos: '10-12', ref: 'Nm 10-12',  testamento: 'AT' },
  { dia: 58, livro: 'Números',      capitulos: '13-15', ref: 'Nm 13-15',  testamento: 'AT' },
  { dia: 59, livro: 'Números',      capitulos: '16-18', ref: 'Nm 16-18',  testamento: 'AT' },
  { dia: 60, livro: 'Números',      capitulos: '19-21', ref: 'Nm 19-21',  testamento: 'AT' },
  { dia: 61, livro: 'Números',      capitulos: '22-24', ref: 'Nm 22-24',  testamento: 'AT' },
  { dia: 62, livro: 'Números',      capitulos: '25-26', ref: 'Nm 25-26',  testamento: 'AT' },
  { dia: 63, livro: 'Números',      capitulos: '27-30', ref: 'Nm 27-30',  testamento: 'AT' },
  { dia: 64, livro: 'Números',      capitulos: '31-33', ref: 'Nm 31-33',  testamento: 'AT' },
  { dia: 65, livro: 'Números',      capitulos: '34-36', ref: 'Nm 34-36',  testamento: 'AT' },
  // DEUTERONÔMIO (dias 66-76)
  { dia: 66, livro: 'Deuteronômio', capitulos: '1-3',   ref: 'Dt 1-3',    testamento: 'AT' },
  { dia: 67, livro: 'Deuteronômio', capitulos: '4-6',   ref: 'Dt 4-6',    testamento: 'AT' },
  { dia: 68, livro: 'Deuteronômio', capitulos: '7-9',   ref: 'Dt 7-9',    testamento: 'AT' },
  { dia: 69, livro: 'Deuteronômio', capitulos: '10-12', ref: 'Dt 10-12',  testamento: 'AT' },
  { dia: 70, livro: 'Deuteronômio', capitulos: '13-15', ref: 'Dt 13-15',  testamento: 'AT' },
  { dia: 71, livro: 'Deuteronômio', capitulos: '16-18', ref: 'Dt 16-18',  testamento: 'AT' },
  { dia: 72, livro: 'Deuteronômio', capitulos: '19-21', ref: 'Dt 19-21',  testamento: 'AT' },
  { dia: 73, livro: 'Deuteronômio', capitulos: '22-24', ref: 'Dt 22-24',  testamento: 'AT' },
  { dia: 74, livro: 'Deuteronômio', capitulos: '25-27', ref: 'Dt 25-27',  testamento: 'AT' },
  { dia: 75, livro: 'Deuteronômio', capitulos: '28-31', ref: 'Dt 28-31',  testamento: 'AT' },
  { dia: 76, livro: 'Deuteronômio', capitulos: '32-34', ref: 'Dt 32-34',  testamento: 'AT' },
  // JOSUÉ (dias 77-83)
  { dia: 77, livro: 'Josué',        capitulos: '1-4',   ref: 'Js 1-4',    testamento: 'AT' },
  { dia: 78, livro: 'Josué',        capitulos: '5-7',   ref: 'Js 5-7',    testamento: 'AT' },
  { dia: 79, livro: 'Josué',        capitulos: '8-10',  ref: 'Js 8-10',   testamento: 'AT' },
  { dia: 80, livro: 'Josué',        capitulos: '11-12', ref: 'Js 11-12',  testamento: 'AT' },
  { dia: 81, livro: 'Josué',        capitulos: '13-16', ref: 'Js 13-16',  testamento: 'AT' },
  { dia: 82, livro: 'Josué',        capitulos: '17-20', ref: 'Js 17-20',  testamento: 'AT' },
  { dia: 83, livro: 'Josué',        capitulos: '21-24', ref: 'Js 21-24',  testamento: 'AT' },
  // JUÍZES (dias 84-90)
  { dia: 84, livro: 'Juízes',       capitulos: '1-3',   ref: 'Jz 1-3',    testamento: 'AT' },
  { dia: 85, livro: 'Juízes',       capitulos: '4-6',   ref: 'Jz 4-6',    testamento: 'AT' },
  { dia: 86, livro: 'Juízes',       capitulos: '7-9',   ref: 'Jz 7-9',    testamento: 'AT' },
  { dia: 87, livro: 'Juízes',       capitulos: '10-12', ref: 'Jz 10-12',  testamento: 'AT' },
  { dia: 88, livro: 'Juízes',       capitulos: '13-15', ref: 'Jz 13-15',  testamento: 'AT' },
  { dia: 89, livro: 'Juízes',       capitulos: '16-18', ref: 'Jz 16-18',  testamento: 'AT' },
  { dia: 90, livro: 'Juízes',       capitulos: '19-21', ref: 'Jz 19-21',  testamento: 'AT' },
  // RUTE
  { dia: 91, livro: 'Rute',         capitulos: '1-4',   ref: 'Rt 1-4',    testamento: 'AT' },
  // I SAMUEL (dias 92-101)
  { dia: 92,  livro: 'I Samuel',    capitulos: '1-3',   ref: '1Sm 1-3',   testamento: 'AT' },
  { dia: 93,  livro: 'I Samuel',    capitulos: '4-6',   ref: '1Sm 4-6',   testamento: 'AT' },
  { dia: 94,  livro: 'I Samuel',    capitulos: '7-9',   ref: '1Sm 7-9',   testamento: 'AT' },
  { dia: 95,  livro: 'I Samuel',    capitulos: '10-12', ref: '1Sm 10-12', testamento: 'AT' },
  { dia: 96,  livro: 'I Samuel',    capitulos: '13-15', ref: '1Sm 13-15', testamento: 'AT' },
  { dia: 97,  livro: 'I Samuel',    capitulos: '16-18', ref: '1Sm 16-18', testamento: 'AT' },
  { dia: 98,  livro: 'I Samuel',    capitulos: '19-21', ref: '1Sm 19-21', testamento: 'AT' },
  { dia: 99,  livro: 'I Samuel',    capitulos: '22-24', ref: '1Sm 22-24', testamento: 'AT' },
  { dia: 100, livro: 'I Samuel',    capitulos: '25-27', ref: '1Sm 25-27', testamento: 'AT' },
  { dia: 101, livro: 'I Samuel',    capitulos: '28-31', ref: '1Sm 28-31', testamento: 'AT' },
  // I CRÔNICAS (dias 102-110)
  { dia: 102, livro: 'I Crônicas',  capitulos: '1-5',   ref: '1Cr 1-5',   testamento: 'AT' },
  { dia: 103, livro: 'I Crônicas',  capitulos: '6-9',   ref: '1Cr 6-9',   testamento: 'AT' },
  { dia: 104, livro: 'I Crônicas',  capitulos: '10-12', ref: '1Cr 10-12', testamento: 'AT' },
  { dia: 105, livro: 'I Crônicas',  capitulos: '13-14', ref: '1Cr 13-14', testamento: 'AT' },
  { dia: 106, livro: 'I Crônicas',  capitulos: '15-17', ref: '1Cr 15-17', testamento: 'AT' },
  { dia: 107, livro: 'I Crônicas',  capitulos: '18-20', ref: '1Cr 18-20', testamento: 'AT' },
  { dia: 108, livro: 'I Crônicas',  capitulos: '21-23', ref: '1Cr 21-23', testamento: 'AT' },
  { dia: 109, livro: 'I Crônicas',  capitulos: '24-26', ref: '1Cr 24-26', testamento: 'AT' },
  { dia: 110, livro: 'I Crônicas',  capitulos: '27-29', ref: '1Cr 27-29', testamento: 'AT' },
  // II SAMUEL (dias 111-117)
  { dia: 111, livro: 'II Samuel',   capitulos: '1-3',   ref: '2Sm 1-3',   testamento: 'AT' },
  { dia: 112, livro: 'II Samuel',   capitulos: '4-6',   ref: '2Sm 4-6',   testamento: 'AT' },
  { dia: 113, livro: 'II Samuel',   capitulos: '7-10',  ref: '2Sm 7-10',  testamento: 'AT' },
  { dia: 114, livro: 'II Samuel',   capitulos: '11-13', ref: '2Sm 11-13', testamento: 'AT' },
  { dia: 115, livro: 'II Samuel',   capitulos: '14-16', ref: '2Sm 14-16', testamento: 'AT' },
  { dia: 116, livro: 'II Samuel',   capitulos: '17-20', ref: '2Sm 17-20', testamento: 'AT' },
  { dia: 117, livro: 'II Samuel',   capitulos: '21-24', ref: '2Sm 21-24', testamento: 'AT' },
  // SALMOS (dias 118-145)
  { dia: 118, livro: 'Salmos',      capitulos: '1-6',    ref: 'Sl 1-6',    testamento: 'AT' },
  { dia: 119, livro: 'Salmos',      capitulos: '7-12',   ref: 'Sl 7-12',   testamento: 'AT' },
  { dia: 120, livro: 'Salmos',      capitulos: '13-18',  ref: 'Sl 13-18',  testamento: 'AT' },
  { dia: 121, livro: 'Salmos',      capitulos: '19-24',  ref: 'Sl 19-24',  testamento: 'AT' },
  { dia: 122, livro: 'Salmos',      capitulos: '25-31',  ref: 'Sl 25-31',  testamento: 'AT' },
  { dia: 123, livro: 'Salmos',      capitulos: '32-36',  ref: 'Sl 32-36',  testamento: 'AT' },
  { dia: 124, livro: 'Salmos',      capitulos: '37-41',  ref: 'Sl 37-41',  testamento: 'AT' },
  { dia: 125, livro: 'Salmos',      capitulos: '42-46',  ref: 'Sl 42-46',  testamento: 'AT' },
  { dia: 126, livro: 'Salmos',      capitulos: '47-51',  ref: 'Sl 47-51',  testamento: 'AT' },
  { dia: 127, livro: 'Salmos',      capitulos: '52-56',  ref: 'Sl 52-56',  testamento: 'AT' },
  { dia: 128, livro: 'Salmos',      capitulos: '57-61',  ref: 'Sl 57-61',  testamento: 'AT' },
  { dia: 129, livro: 'Salmos',      capitulos: '62-65',  ref: 'Sl 62-65',  testamento: 'AT' },
  { dia: 130, livro: 'Salmos',      capitulos: '66-68',  ref: 'Sl 66-68',  testamento: 'AT' },
  { dia: 131, livro: 'Salmos',      capitulos: '69-72',  ref: 'Sl 69-72',  testamento: 'AT' },
  { dia: 132, livro: 'Salmos',      capitulos: '73-77',  ref: 'Sl 73-77',  testamento: 'AT' },
  { dia: 133, livro: 'Salmos',      capitulos: '78-82',  ref: 'Sl 78-82',  testamento: 'AT' },
  { dia: 134, livro: 'Salmos',      capitulos: '83-88',  ref: 'Sl 83-88',  testamento: 'AT' },
  { dia: 135, livro: 'Salmos',      capitulos: '89-91',  ref: 'Sl 89-91',  testamento: 'AT' },
  { dia: 136, livro: 'Salmos',      capitulos: '92-98',  ref: 'Sl 92-98',  testamento: 'AT' },
  { dia: 137, livro: 'Salmos',      capitulos: '99-104', ref: 'Sl 99-104', testamento: 'AT' },
  { dia: 138, livro: 'Salmos',      capitulos: '105-106',ref: 'Sl 105-106',testamento: 'AT' },
  { dia: 139, livro: 'Salmos',      capitulos: '107-110',ref: 'Sl 107-110',testamento: 'AT' },
  { dia: 140, livro: 'Salmos',      capitulos: '111-118',ref: 'Sl 111-118',testamento: 'AT' },
  { dia: 141, livro: 'Salmos',      capitulos: '119',    ref: 'Sl 119',    testamento: 'AT' },
  { dia: 142, livro: 'Salmos',      capitulos: '120-130',ref: 'Sl 120-130',testamento: 'AT' },
  { dia: 143, livro: 'Salmos',      capitulos: '131-138',ref: 'Sl 131-138',testamento: 'AT' },
  { dia: 144, livro: 'Salmos',      capitulos: '139-144',ref: 'Sl 139-144',testamento: 'AT' },
  { dia: 145, livro: 'Salmos',      capitulos: '145-150',ref: 'Sl 145-150',testamento: 'AT' },
  // I REIS (dias 146-152)
  { dia: 146, livro: 'I Reis',      capitulos: '1-4',   ref: '1Rs 1-4',   testamento: 'AT' },
  { dia: 147, livro: 'I Reis',      capitulos: '5-8',   ref: '1Rs 5-8',   testamento: 'AT' },
  { dia: 148, livro: 'I Reis',      capitulos: '9-11',  ref: '1Rs 9-11',  testamento: 'AT' },
  { dia: 149, livro: 'I Reis',      capitulos: '12-14', ref: '1Rs 12-14', testamento: 'AT' },
  { dia: 150, livro: 'I Reis',      capitulos: '15-17', ref: '1Rs 15-17', testamento: 'AT' },
  { dia: 151, livro: 'I Reis',      capitulos: '18-20', ref: '1Rs 18-20', testamento: 'AT' },
  { dia: 152, livro: 'I Reis',      capitulos: '21-22', ref: '1Rs 21-22', testamento: 'AT' },
  // PROVÉRBIOS (dias 153-162)
  { dia: 153, livro: 'Provérbios',  capitulos: '1-4',   ref: 'Pv 1-4',    testamento: 'AT' },
  { dia: 154, livro: 'Provérbios',  capitulos: '5-7',   ref: 'Pv 5-7',    testamento: 'AT' },
  { dia: 155, livro: 'Provérbios',  capitulos: '8-10',  ref: 'Pv 8-10',   testamento: 'AT' },
  { dia: 156, livro: 'Provérbios',  capitulos: '11-13', ref: 'Pv 11-13',  testamento: 'AT' },
  { dia: 157, livro: 'Provérbios',  capitulos: '14-16', ref: 'Pv 14-16',  testamento: 'AT' },
  { dia: 158, livro: 'Provérbios',  capitulos: '17-19', ref: 'Pv 17-19',  testamento: 'AT' },
  { dia: 159, livro: 'Provérbios',  capitulos: '20-22', ref: 'Pv 20-22',  testamento: 'AT' },
  { dia: 160, livro: 'Provérbios',  capitulos: '23-25', ref: 'Pv 23-25',  testamento: 'AT' },
  { dia: 161, livro: 'Provérbios',  capitulos: '26-28', ref: 'Pv 26-28',  testamento: 'AT' },
  { dia: 162, livro: 'Provérbios',  capitulos: '29-31', ref: 'Pv 29-31',  testamento: 'AT' },
  // CÂNTICOS (dias 163-165)
  { dia: 163, livro: 'Cânticos',    capitulos: '1-3',   ref: 'Ct 1-3',    testamento: 'AT' },
  { dia: 164, livro: 'Cânticos',    capitulos: '4-6',   ref: 'Ct 4-6',    testamento: 'AT' },
  { dia: 165, livro: 'Cânticos',    capitulos: '7-8',   ref: 'Ct 7-8',    testamento: 'AT' },
  // ECLESIASTES (dias 166-169)
  { dia: 166, livro: 'Eclesiastes', capitulos: '1-3',   ref: 'Ec 1-3',    testamento: 'AT' },
  { dia: 167, livro: 'Eclesiastes', capitulos: '4-6',   ref: 'Ec 4-6',    testamento: 'AT' },
  { dia: 168, livro: 'Eclesiastes', capitulos: '7-9',   ref: 'Ec 7-9',    testamento: 'AT' },
  { dia: 169, livro: 'Eclesiastes', capitulos: '10-12', ref: 'Ec 10-12',  testamento: 'AT' },
  // II CRÔNICAS (dias 170-180)
  { dia: 170, livro: 'II Crônicas', capitulos: '1-3',   ref: '2Cr 1-3',   testamento: 'AT' },
  { dia: 171, livro: 'II Crônicas', capitulos: '4-6',   ref: '2Cr 4-6',   testamento: 'AT' },
  { dia: 172, livro: 'II Crônicas', capitulos: '7-9',   ref: '2Cr 7-9',   testamento: 'AT' },
  { dia: 173, livro: 'II Crônicas', capitulos: '10-12', ref: '2Cr 10-12', testamento: 'AT' },
  { dia: 174, livro: 'II Crônicas', capitulos: '13-15', ref: '2Cr 13-15', testamento: 'AT' },
  { dia: 175, livro: 'II Crônicas', capitulos: '16-19', ref: '2Cr 16-19', testamento: 'AT' },
  { dia: 176, livro: 'II Crônicas', capitulos: '20-23', ref: '2Cr 20-23', testamento: 'AT' },
  { dia: 177, livro: 'II Crônicas', capitulos: '24-27', ref: '2Cr 24-27', testamento: 'AT' },
  { dia: 178, livro: 'II Crônicas', capitulos: '28-30', ref: '2Cr 28-30', testamento: 'AT' },
  { dia: 179, livro: 'II Crônicas', capitulos: '31-33', ref: '2Cr 31-33', testamento: 'AT' },
  { dia: 180, livro: 'II Crônicas', capitulos: '34-36', ref: '2Cr 34-36', testamento: 'AT' },
  // II REIS (dias 181-188)
  { dia: 181, livro: 'II Reis',     capitulos: '1-4',   ref: '2Rs 1-4',   testamento: 'AT' },
  { dia: 182, livro: 'II Reis',     capitulos: '5-7',   ref: '2Rs 5-7',   testamento: 'AT' },
  { dia: 183, livro: 'II Reis',     capitulos: '8-10',  ref: '2Rs 8-10',  testamento: 'AT' },
  { dia: 184, livro: 'II Reis',     capitulos: '11-13', ref: '2Rs 11-13', testamento: 'AT' },
  { dia: 185, livro: 'II Reis',     capitulos: '14-16', ref: '2Rs 14-16', testamento: 'AT' },
  { dia: 186, livro: 'II Reis',     capitulos: '17-19', ref: '2Rs 17-19', testamento: 'AT' },
  { dia: 187, livro: 'II Reis',     capitulos: '20-22', ref: '2Rs 20-22', testamento: 'AT' },
  { dia: 188, livro: 'II Reis',     capitulos: '23-25', ref: '2Rs 23-25', testamento: 'AT' },
  // PROFETAS MENORES
  { dia: 189, livro: 'Obadias + Joel', capitulos: 'Ob 1 / Jl 1-3', ref: 'Ob + Jl', testamento: 'AT' },
  { dia: 190, livro: 'Jonas',       capitulos: '1-4',   ref: 'Jn 1-4',    testamento: 'AT' },
  { dia: 191, livro: 'Amós',        capitulos: '1-3',   ref: 'Am 1-3',    testamento: 'AT' },
  { dia: 192, livro: 'Amós',        capitulos: '4-6',   ref: 'Am 4-6',    testamento: 'AT' },
  { dia: 193, livro: 'Amós',        capitulos: '7-9',   ref: 'Am 7-9',    testamento: 'AT' },
  { dia: 194, livro: 'Oseias',      capitulos: '1-4',   ref: 'Os 1-4',    testamento: 'AT' },
  { dia: 195, livro: 'Oseias',      capitulos: '5-9',   ref: 'Os 5-9',    testamento: 'AT' },
  { dia: 196, livro: 'Oseias',      capitulos: '10-14', ref: 'Os 10-14',  testamento: 'AT' },
  // ISAÍAS (dias 197-214)
  { dia: 197, livro: 'Isaías',      capitulos: '1-3',   ref: 'Is 1-3',    testamento: 'AT' },
  { dia: 198, livro: 'Isaías',      capitulos: '4-6',   ref: 'Is 4-6',    testamento: 'AT' },
  { dia: 199, livro: 'Isaías',      capitulos: '7-9',   ref: 'Is 7-9',    testamento: 'AT' },
  { dia: 200, livro: 'Isaías',      capitulos: '10-12', ref: 'Is 10-12',  testamento: 'AT' },
  { dia: 201, livro: 'Isaías',      capitulos: '13-16', ref: 'Is 13-16',  testamento: 'AT' },
  { dia: 202, livro: 'Isaías',      capitulos: '17-20', ref: 'Is 17-20',  testamento: 'AT' },
  { dia: 203, livro: 'Isaías',      capitulos: '21-24', ref: 'Is 21-24',  testamento: 'AT' },
  { dia: 204, livro: 'Isaías',      capitulos: '25-28', ref: 'Is 25-28',  testamento: 'AT' },
  { dia: 205, livro: 'Isaías',      capitulos: '29-31', ref: 'Is 29-31',  testamento: 'AT' },
  { dia: 206, livro: 'Isaías',      capitulos: '32-35', ref: 'Is 32-35',  testamento: 'AT' },
  { dia: 207, livro: 'Isaías',      capitulos: '36-39', ref: 'Is 36-39',  testamento: 'AT' },
  { dia: 208, livro: 'Isaías',      capitulos: '40-42', ref: 'Is 40-42',  testamento: 'AT' },
  { dia: 209, livro: 'Isaías',      capitulos: '43-45', ref: 'Is 43-45',  testamento: 'AT' },
  { dia: 210, livro: 'Isaías',      capitulos: '46-48', ref: 'Is 46-48',  testamento: 'AT' },
  { dia: 211, livro: 'Isaías',      capitulos: '49-52', ref: 'Is 49-52',  testamento: 'AT' },
  { dia: 212, livro: 'Isaías',      capitulos: '53-58', ref: 'Is 53-58',  testamento: 'AT' },
  { dia: 213, livro: 'Isaías',      capitulos: '59-63', ref: 'Is 59-63',  testamento: 'AT' },
  { dia: 214, livro: 'Isaías',      capitulos: '64-66', ref: 'Is 64-66',  testamento: 'AT' },
  // MIQUEIAS
  { dia: 215, livro: 'Miqueias',    capitulos: '1-4',   ref: 'Mq 1-4',    testamento: 'AT' },
  { dia: 216, livro: 'Miqueias',    capitulos: '5-7',   ref: 'Mq 5-7',    testamento: 'AT' },
  { dia: 217, livro: 'Naum',        capitulos: '1-3',   ref: 'Na 1-3',    testamento: 'AT' },
  { dia: 218, livro: 'Sofonias',    capitulos: '1-3',   ref: 'Sf 1-3',    testamento: 'AT' },
  // JEREMIAS (dias 219-232)
  { dia: 219, livro: 'Jeremias',    capitulos: '1-4',   ref: 'Jr 1-4',    testamento: 'AT' },
  { dia: 220, livro: 'Jeremias',    capitulos: '5-7',   ref: 'Jr 5-7',    testamento: 'AT' },
  { dia: 221, livro: 'Jeremias',    capitulos: '8-11',  ref: 'Jr 8-11',   testamento: 'AT' },
  { dia: 222, livro: 'Jeremias',    capitulos: '12-16', ref: 'Jr 12-16',  testamento: 'AT' },
  { dia: 223, livro: 'Jeremias',    capitulos: '17-19', ref: 'Jr 17-19',  testamento: 'AT' },
  { dia: 224, livro: 'Jeremias',    capitulos: '20-22', ref: 'Jr 20-22',  testamento: 'AT' },
  { dia: 225, livro: 'Jeremias',    capitulos: '23-25', ref: 'Jr 23-25',  testamento: 'AT' },
  { dia: 226, livro: 'Jeremias',    capitulos: '26-28', ref: 'Jr 26-28',  testamento: 'AT' },
  { dia: 227, livro: 'Jeremias',    capitulos: '29-31', ref: 'Jr 29-31',  testamento: 'AT' },
  { dia: 228, livro: 'Jeremias',    capitulos: '32-35', ref: 'Jr 32-35',  testamento: 'AT' },
  { dia: 229, livro: 'Jeremias',    capitulos: '36-40', ref: 'Jr 36-40',  testamento: 'AT' },
  { dia: 230, livro: 'Jeremias',    capitulos: '41-45', ref: 'Jr 41-45',  testamento: 'AT' },
  { dia: 231, livro: 'Jeremias',    capitulos: '46-49', ref: 'Jr 46-49',  testamento: 'AT' },
  { dia: 232, livro: 'Jeremias',    capitulos: '50-52', ref: 'Jr 50-52',  testamento: 'AT' },
  { dia: 233, livro: 'Lamentações', capitulos: '1-5',   ref: 'Lm 1-5',    testamento: 'AT' },
  { dia: 234, livro: 'Habacuque',   capitulos: '1-3',   ref: 'Hc 1-3',    testamento: 'AT' },
  // DANIEL (dias 235-238)
  { dia: 235, livro: 'Daniel',      capitulos: '1-3',   ref: 'Dn 1-3',    testamento: 'AT' },
  { dia: 236, livro: 'Daniel',      capitulos: '4-6',   ref: 'Dn 4-6',    testamento: 'AT' },
  { dia: 237, livro: 'Daniel',      capitulos: '7-9',   ref: 'Dn 7-9',    testamento: 'AT' },
  { dia: 238, livro: 'Daniel',      capitulos: '10-12', ref: 'Dn 10-12',  testamento: 'AT' },
  // EZEQUIEL (dias 239-254)
  { dia: 239, livro: 'Ezequiel',    capitulos: '1-3',   ref: 'Ez 1-3',    testamento: 'AT' },
  { dia: 240, livro: 'Ezequiel',    capitulos: '4-6',   ref: 'Ez 4-6',    testamento: 'AT' },
  { dia: 241, livro: 'Ezequiel',    capitulos: '7-9',   ref: 'Ez 7-9',    testamento: 'AT' },
  { dia: 242, livro: 'Ezequiel',    capitulos: '10-12', ref: 'Ez 10-12',  testamento: 'AT' },
  { dia: 243, livro: 'Ezequiel',    capitulos: '13-15', ref: 'Ez 13-15',  testamento: 'AT' },
  { dia: 244, livro: 'Ezequiel',    capitulos: '16-18', ref: 'Ez 16-18',  testamento: 'AT' },
  { dia: 245, livro: 'Ezequiel',    capitulos: '19-21', ref: 'Ez 19-21',  testamento: 'AT' },
  { dia: 246, livro: 'Ezequiel',    capitulos: '22-24', ref: 'Ez 22-24',  testamento: 'AT' },
  { dia: 247, livro: 'Ezequiel',    capitulos: '25-27', ref: 'Ez 25-27',  testamento: 'AT' },
  { dia: 248, livro: 'Ezequiel',    capitulos: '28-30', ref: 'Ez 28-30',  testamento: 'AT' },
  { dia: 249, livro: 'Ezequiel',    capitulos: '31-33', ref: 'Ez 31-33',  testamento: 'AT' },
  { dia: 250, livro: 'Ezequiel',    capitulos: '34-36', ref: 'Ez 34-36',  testamento: 'AT' },
  { dia: 251, livro: 'Ezequiel',    capitulos: '37-39', ref: 'Ez 37-39',  testamento: 'AT' },
  { dia: 252, livro: 'Ezequiel',    capitulos: '40-42', ref: 'Ez 40-42',  testamento: 'AT' },
  { dia: 253, livro: 'Ezequiel',    capitulos: '43-45', ref: 'Ez 43-45',  testamento: 'AT' },
  { dia: 254, livro: 'Ezequiel',    capitulos: '46-48', ref: 'Ez 46-48',  testamento: 'AT' },
  { dia: 255, livro: 'Ageu',        capitulos: '1-2',   ref: 'Ag 1-2',    testamento: 'AT' },
  { dia: 256, livro: 'Zacarias',    capitulos: '1-2',   ref: 'Zc 1-2',    testamento: 'AT' },
  { dia: 257, livro: 'Zacarias',    capitulos: '3-5',   ref: 'Zc 3-5',    testamento: 'AT' },
  { dia: 258, livro: 'Zacarias',    capitulos: '6-8',   ref: 'Zc 6-8',    testamento: 'AT' },
  { dia: 259, livro: 'Zacarias',    capitulos: '9-11',  ref: 'Zc 9-11',   testamento: 'AT' },
  { dia: 260, livro: 'Zacarias',    capitulos: '12-14', ref: 'Zc 12-14',  testamento: 'AT' },
  { dia: 261, livro: 'Ester',       capitulos: '1-4',   ref: 'Et 1-4',    testamento: 'AT' },
  { dia: 262, livro: 'Ester',       capitulos: '5-7',   ref: 'Et 5-7',    testamento: 'AT' },
  { dia: 263, livro: 'Ester',       capitulos: '8-10',  ref: 'Et 8-10',   testamento: 'AT' },
  { dia: 264, livro: 'Esdras',      capitulos: '1-4',   ref: 'Ed 1-4',    testamento: 'AT' },
  { dia: 265, livro: 'Esdras',      capitulos: '5-7',   ref: 'Ed 5-7',    testamento: 'AT' },
  { dia: 266, livro: 'Esdras',      capitulos: '8-10',  ref: 'Ed 8-10',   testamento: 'AT' },
  { dia: 267, livro: 'Neemias',     capitulos: '1-4',   ref: 'Ne 1-4',    testamento: 'AT' },
  { dia: 268, livro: 'Neemias',     capitulos: '5-7',   ref: 'Ne 5-7',    testamento: 'AT' },
  { dia: 269, livro: 'Neemias',     capitulos: '8-10',  ref: 'Ne 8-10',   testamento: 'AT' },
  { dia: 270, livro: 'Neemias',     capitulos: '11-13', ref: 'Ne 11-13',  testamento: 'AT' },
  { dia: 271, livro: 'Malaquias',   capitulos: '1-2',   ref: 'Ml 1-2',    testamento: 'AT' },
  { dia: 272, livro: 'Malaquias',   capitulos: '3-4',   ref: 'Ml 3-4',    testamento: 'AT' },
  // NOVO TESTAMENTO
  { dia: 273, livro: 'João',        capitulos: '1-3',   ref: 'Jo 1-3',    testamento: 'NT' },
  { dia: 274, livro: 'João',        capitulos: '4-6',   ref: 'Jo 4-6',    testamento: 'NT' },
  { dia: 275, livro: 'João',        capitulos: '7-9',   ref: 'Jo 7-9',    testamento: 'NT' },
  { dia: 276, livro: 'João',        capitulos: '10-12', ref: 'Jo 10-12',  testamento: 'NT' },
  { dia: 277, livro: 'João',        capitulos: '13-15', ref: 'Jo 13-15',  testamento: 'NT' },
  { dia: 278, livro: 'João',        capitulos: '16-18', ref: 'Jo 16-18',  testamento: 'NT' },
  { dia: 279, livro: 'João',        capitulos: '19-21', ref: 'Jo 19-21',  testamento: 'NT' },
  { dia: 280, livro: 'Lucas',       capitulos: '1-3',   ref: 'Lc 1-3',    testamento: 'NT' },
  { dia: 281, livro: 'Lucas',       capitulos: '4-6',   ref: 'Lc 4-6',    testamento: 'NT' },
  { dia: 282, livro: 'Lucas',       capitulos: '7-9',   ref: 'Lc 7-9',    testamento: 'NT' },
  { dia: 283, livro: 'Lucas',       capitulos: '10-12', ref: 'Lc 10-12',  testamento: 'NT' },
  { dia: 284, livro: 'Lucas',       capitulos: '13-16', ref: 'Lc 13-16',  testamento: 'NT' },
  { dia: 285, livro: 'Lucas',       capitulos: '17-20', ref: 'Lc 17-20',  testamento: 'NT' },
  { dia: 286, livro: 'Lucas',       capitulos: '21-24', ref: 'Lc 21-24',  testamento: 'NT' },
  { dia: 287, livro: 'Mateus',      capitulos: '1-4',   ref: 'Mt 1-4',    testamento: 'NT' },
  { dia: 288, livro: 'Mateus',      capitulos: '5-7',   ref: 'Mt 5-7',    testamento: 'NT' },
  { dia: 289, livro: 'Mateus',      capitulos: '8-9',   ref: 'Mt 8-9',    testamento: 'NT' },
  { dia: 290, livro: 'Mateus',      capitulos: '10-12', ref: 'Mt 10-12',  testamento: 'NT' },
  { dia: 291, livro: 'Mateus',      capitulos: '13-15', ref: 'Mt 13-15',  testamento: 'NT' },
  { dia: 292, livro: 'Mateus',      capitulos: '16-18', ref: 'Mt 16-18',  testamento: 'NT' },
  { dia: 293, livro: 'Mateus',      capitulos: '19-20', ref: 'Mt 19-20',  testamento: 'NT' },
  { dia: 294, livro: 'Mateus',      capitulos: '21-24', ref: 'Mt 21-24',  testamento: 'NT' },
  { dia: 295, livro: 'Mateus',      capitulos: '25-28', ref: 'Mt 25-28',  testamento: 'NT' },
  { dia: 296, livro: 'Marcos',      capitulos: '1-4',   ref: 'Mc 1-4',    testamento: 'NT' },
  { dia: 297, livro: 'Marcos',      capitulos: '5-7',   ref: 'Mc 5-7',    testamento: 'NT' },
  { dia: 298, livro: 'Marcos',      capitulos: '8-10',  ref: 'Mc 8-10',   testamento: 'NT' },
  { dia: 299, livro: 'Marcos',      capitulos: '11-13', ref: 'Mc 11-13',  testamento: 'NT' },
  { dia: 300, livro: 'Marcos',      capitulos: '14-16', ref: 'Mc 14-16',  testamento: 'NT' },
  { dia: 301, livro: 'Atos',        capitulos: '1-4',   ref: 'At 1-4',    testamento: 'NT' },
  { dia: 302, livro: 'Atos',        capitulos: '5-7',   ref: 'At 5-7',    testamento: 'NT' },
  { dia: 303, livro: 'Atos',        capitulos: '8-9',   ref: 'At 8-9',    testamento: 'NT' },
  { dia: 304, livro: 'Atos',        capitulos: '10-12', ref: 'At 10-12',  testamento: 'NT' },
  { dia: 305, livro: 'Atos',        capitulos: '13-15', ref: 'At 13-15',  testamento: 'NT' },
  { dia: 306, livro: 'Atos',        capitulos: '16-17', ref: 'At 16-17',  testamento: 'NT' },
  { dia: 307, livro: 'Atos',        capitulos: '18-20', ref: 'At 18-20',  testamento: 'NT' },
  { dia: 308, livro: 'Atos',        capitulos: '21-24', ref: 'At 21-24',  testamento: 'NT' },
  { dia: 309, livro: 'Atos',        capitulos: '25-28', ref: 'At 25-28',  testamento: 'NT' },
  { dia: 310, livro: 'Tiago',              capitulos: '1-5',   ref: 'Tg 1-5',    testamento: 'NT' },
  { dia: 311, livro: 'Gálatas',            capitulos: '1-3',   ref: 'Gl 1-3',    testamento: 'NT' },
  { dia: 312, livro: 'Gálatas',            capitulos: '4-6',   ref: 'Gl 4-6',    testamento: 'NT' },
  { dia: 313, livro: 'I Tessalonicenses',  capitulos: '1-5',   ref: '1Ts 1-5',   testamento: 'NT' },
  { dia: 314, livro: 'II Tessalonicenses', capitulos: '1-3',   ref: '2Ts 1-3',   testamento: 'NT' },
  { dia: 315, livro: 'I Coríntios',        capitulos: '1-4',   ref: '1Co 1-4',   testamento: 'NT' },
  { dia: 316, livro: 'I Coríntios',        capitulos: '5-8',   ref: '1Co 5-8',   testamento: 'NT' },
  { dia: 317, livro: 'I Coríntios',        capitulos: '9-12',  ref: '1Co 9-12',  testamento: 'NT' },
  { dia: 318, livro: 'I Coríntios',        capitulos: '13-16', ref: '1Co 13-16', testamento: 'NT' },
  { dia: 319, livro: 'II Coríntios',       capitulos: '1-4',   ref: '2Co 1-4',   testamento: 'NT' },
  { dia: 320, livro: 'II Coríntios',       capitulos: '5-8',   ref: '2Co 5-8',   testamento: 'NT' },
  { dia: 321, livro: 'II Coríntios',       capitulos: '9-13',  ref: '2Co 9-13',  testamento: 'NT' },
  { dia: 322, livro: 'Romanos',            capitulos: '1-3',   ref: 'Rm 1-3',    testamento: 'NT' },
  { dia: 323, livro: 'Romanos',            capitulos: '4-7',   ref: 'Rm 4-7',    testamento: 'NT' },
  { dia: 324, livro: 'Romanos',            capitulos: '8-10',  ref: 'Rm 8-10',   testamento: 'NT' },
  { dia: 325, livro: 'Romanos',            capitulos: '11-13', ref: 'Rm 11-13',  testamento: 'NT' },
  { dia: 326, livro: 'Romanos',            capitulos: '14-16', ref: 'Rm 14-16',  testamento: 'NT' },
  { dia: 327, livro: 'Efésios',            capitulos: '1-3',   ref: 'Ef 1-3',    testamento: 'NT' },
  { dia: 328, livro: 'Efésios',            capitulos: '4-6',   ref: 'Ef 4-6',    testamento: 'NT' },
  { dia: 329, livro: 'Colossenses',        capitulos: '1-4',   ref: 'Cl 1-4',    testamento: 'NT' },
  { dia: 330, livro: 'Filemom',            capitulos: '1',     ref: 'Fm 1',      testamento: 'NT' },
  { dia: 331, livro: 'Filipenses',         capitulos: '1-2',   ref: 'Fp 1-2',    testamento: 'NT' },
  { dia: 332, livro: 'Filipenses',         capitulos: '3-4',   ref: 'Fp 3-4',    testamento: 'NT' },
  { dia: 333, livro: 'I Pedro',            capitulos: '1-5',   ref: '1Pe 1-5',   testamento: 'NT' },
  { dia: 334, livro: 'I Timóteo',          capitulos: '1-3',   ref: '1Tm 1-3',   testamento: 'NT' },
  { dia: 335, livro: 'I Timóteo',          capitulos: '4-6',   ref: '1Tm 4-6',   testamento: 'NT' },
  { dia: 336, livro: 'Tito',               capitulos: '1-3',   ref: 'Tt 1-3',    testamento: 'NT' },
  { dia: 337, livro: 'II Pedro',           capitulos: '1-3',   ref: '2Pe 1-3',   testamento: 'NT' },
  { dia: 338, livro: 'Judas',              capitulos: '1',     ref: 'Jd 1',      testamento: 'NT' },
  { dia: 339, livro: 'II Timóteo',         capitulos: '1-4',   ref: '2Tm 1-4',   testamento: 'NT' },
  { dia: 340, livro: 'Hebreus',            capitulos: '1-4',   ref: 'Hb 1-4',    testamento: 'NT' },
  { dia: 341, livro: 'Hebreus',            capitulos: '5-7',   ref: 'Hb 5-7',    testamento: 'NT' },
  { dia: 342, livro: 'Hebreus',            capitulos: '8-10',  ref: 'Hb 8-10',   testamento: 'NT' },
  { dia: 343, livro: 'Hebreus',            capitulos: '11-13', ref: 'Hb 11-13',  testamento: 'NT' },
  { dia: 344, livro: 'I João',             capitulos: '1-3',   ref: '1Jo 1-3',   testamento: 'NT' },
  { dia: 345, livro: 'I João + II João',   capitulos: '4-5 + II Jo', ref: '1Jo 4-5 + 2Jo', testamento: 'NT' },
  { dia: 346, livro: 'III João',           capitulos: '1',     ref: '3Jo 1',     testamento: 'NT' },
  { dia: 347, livro: 'Apocalipse',         capitulos: '1-3',   ref: 'Ap 1-3',    testamento: 'NT' },
  { dia: 348, livro: 'Apocalipse',         capitulos: '4-6',   ref: 'Ap 4-6',    testamento: 'NT' },
  { dia: 349, livro: 'Apocalipse',         capitulos: '7-9',   ref: 'Ap 7-9',    testamento: 'NT' },
  { dia: 350, livro: 'Apocalipse',         capitulos: '10-12', ref: 'Ap 10-12',  testamento: 'NT' },
  { dia: 351, livro: 'Apocalipse',         capitulos: '13-15', ref: 'Ap 13-15',  testamento: 'NT' },
  { dia: 352, livro: 'Apocalipse',         capitulos: '16-18', ref: 'Ap 16-18',  testamento: 'NT' },
  { dia: 353, livro: 'Apocalipse',         capitulos: '19-22', ref: 'Ap 19-22',  testamento: 'NT' },
]

export function getDiaPlano(dia: number): DiaPlano | undefined {
  return PLANO_LEITURA.find(d => d.dia === dia)
}

export function getTotalDias(): number {
  return PLANO_LEITURA.length
}

export function getPorcentagem(diasLidos: number[]): number {
  return Math.round((diasLidos.length / PLANO_LEITURA.length) * 100)
}
